AWSTemplateFormatVersion: "2010-09-09"
Description: "My CloudFormation Template"
Resources:
  s3Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: Private
      BucketName: fongangs-bucket1